# Generated by Django 4.2.5 on 2024-09-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.CharField(max_length=10)),
                ("item_name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=10)),
                ("barcode", models.CharField(max_length=10)),
                ("supplier", models.CharField(max_length=10)),
                ("min_stock", models.IntegerField(default=0)),
                ("max_stock", models.IntegerField(default=0)),
                ("cur_stock", models.IntegerField(default=0)),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tax", models.DecimalField(decimal_places=2, max_digits=5)),
                ("date_added", models.DateField(max_length=10)),
                ("last_updated", models.DateTimeField(max_length=10)),
                ("is_active", models.BooleanField(max_length=10)),
            ],
            options={
                "db_table": "item_details",
            },
        ),
    ]
