# Generated by Django 4.2.5 on 2024-09-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemdetails",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
